"""add_updated_at_to_health_profile

Revision ID: 4206b7f5f4f7
Revises: 002
Create Date: 2026-07-24 12:40:51.611281
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4206b7f5f4f7'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety_routes')
    op.alter_column('emergency_contacts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('emergency_contacts', 'notify_sms',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('emergency_contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=False)
    op.alter_column('mood_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('mood_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mood_user_date'), table_name='mood_logs')
    op.drop_constraint(op.f('uq_mood_user_date'), 'mood_logs', type_='unique')
    op.create_index(op.f('ix_mood_logs_user_id'), 'mood_logs', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_mood_date', 'mood_logs', ['user_id', 'date'])
    op.alter_column('pcod_analyses', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pcod_analyses', 'symptoms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('pcod_analyses', 'lifestyle_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('pcod_analyses', 'lab_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('pcod_analyses', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('pcod_analyses', 'driver_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('pcod_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_pcod_user_created'), table_name='pcod_analyses')
    op.create_index(op.f('ix_pcod_analyses_user_id'), 'pcod_analyses', ['user_id'], unique=False)
    op.alter_column('period_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_period_user_start'), table_name='period_logs')
    op.drop_constraint(op.f('uq_period_user_start'), 'period_logs', type_='unique')
    op.create_index(op.f('ix_period_logs_user_id'), 'period_logs', ['user_id'], unique=False)
    op.alter_column('period_symptoms', 'symptoms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('period_symptoms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_symptom_user_date'), 'period_symptoms', type_='unique')
    op.create_index(op.f('ix_period_symptoms_user_id'), 'period_symptoms', ['user_id'], unique=False)
    op.alter_column('sos_events', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sos_events', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sos_events', 'acknowledged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('sos_events', 'contacts_notified',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('sos_events', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_sos_events_user_id'), 'sos_events', ['user_id'], unique=False)
    op.add_column('user_health_profile', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('user_health_profile', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_health_profile', 'cycle_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_health_profile', 'health_goals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('user_health_profile', 'onboarding_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_health_profile', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('user_health_profile_user_id_key'), 'user_health_profile', type_='unique')
    op.create_index(op.f('ix_user_health_profile_user_id'), 'user_health_profile', ['user_id'], unique=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_health_profile_user_id'), table_name='user_health_profile')
    op.create_unique_constraint(op.f('user_health_profile_user_id_key'), 'user_health_profile', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_health_profile', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_health_profile', 'onboarding_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_health_profile', 'health_goals',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_health_profile', 'cycle_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_health_profile', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('user_health_profile', 'updated_at')
    op.drop_index(op.f('ix_sos_events_user_id'), table_name='sos_events')
    op.alter_column('sos_events', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sos_events', 'contacts_notified',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('sos_events', 'acknowledged_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sos_events', 'triggered_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sos_events', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_period_symptoms_user_id'), table_name='period_symptoms')
    op.create_unique_constraint(op.f('uq_symptom_user_date'), 'period_symptoms', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('period_symptoms', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('period_symptoms', 'symptoms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_period_logs_user_id'), table_name='period_logs')
    op.create_unique_constraint(op.f('uq_period_user_start'), 'period_logs', ['user_id', 'start_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_period_user_start'), 'period_logs', ['user_id', sa.literal_column('start_date DESC')], unique=False)
    op.alter_column('period_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pcod_analyses_user_id'), table_name='pcod_analyses')
    op.create_index(op.f('idx_pcod_user_created'), 'pcod_analyses', ['user_id', 'created_at'], unique=False)
    op.alter_column('pcod_analyses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pcod_analyses', 'driver_breakdown',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('pcod_analyses', 'recommendations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('pcod_analyses', 'lab_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('pcod_analyses', 'lifestyle_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('pcod_analyses', 'symptoms',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('pcod_analyses', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_user_mood_date', 'mood_logs', type_='unique')
    op.drop_index(op.f('ix_mood_logs_user_id'), table_name='mood_logs')
    op.create_unique_constraint(op.f('uq_mood_user_date'), 'mood_logs', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_mood_user_date'), 'mood_logs', ['user_id', sa.literal_column('date DESC')], unique=False)
    op.alter_column('mood_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mood_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.alter_column('emergency_contacts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('emergency_contacts', 'notify_sms',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('emergency_contacts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('safety_routes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('origin_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('destination_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('origin_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('origin_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('destination_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('destination_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('route_geojson', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('safety_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('safety_routes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('safety_routes_pkey'))
    )
    # ### end Alembic commands ###
